import { useGuitarBodyContext } from "../../hooks/useGuitarBody";
import { useGuitarNeckContext } from "../../hooks/useGuitarNeck";
import Bursts from "./BurstCodes.json";
import Patterns from "./Patterns";

const Guitar = () => {
  const {
    color,
    burst,
    texture,
    bodyPaintOpacity,
    burstColor,
    hasPickguard,
    pickguardColor,
  } = useGuitarBodyContext();

  const { fretboardWood, inlaysColor, nutColor } = useGuitarNeckContext();

  return (
    <>
      {/* Code generated by Adobe Illustrator, modified to make it dynamic */}
      <svg viewBox="0 0 347.71 115.24">
        <defs>
          <Patterns color={color} bodyPaintOpacity={bodyPaintOpacity} />
          <linearGradient
            id="linear-gradient"
            x1="0"
            y1="57.62"
            x2="144.43"
            y2="57.62"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#fff" stop-opacity="0" />
            <stop offset="1" stopColor="#fff" stop-opacity="0" />
          </linearGradient>
          <filter
            id="luminosity-invert"
            x="-2.15"
            y="-2.04"
            width="148.8"
            height="119.28"
            color-interpolation-filters="sRGB"
            filterUnits="userSpaceOnUse"
          >
            <feColorMatrix
              result="cm"
              values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"
            />
          </filter>
          <mask
            id="mask"
            x="-2.15"
            y="-2.04"
            width="148.8"
            height="119.28"
            maskUnits="userSpaceOnUse"
          >
            <g filter="url(#luminosity-invert)">
              <image
                width="620"
                height="497"
                transform="translate(-2.15 -2.04) scale(.24)"
                xlinkHref={Bursts.telecasterBurst}
              />
            </g>
          </mask>
          <linearGradient
            id="Pewter"
            x1="299.35"
            y1="47.21"
            x2="301.35"
            y2="47.21"
            gradientTransform="translate(-1.15 86.42) rotate(-16.34)"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset=".03" stopColor="#9b9b98" />
            <stop offset=".13" stopColor="#a4a5a6" />
            <stop offset=".22" stopColor="#aeb0b7" />
            <stop offset=".35" stopColor="#9fa3a9" />
            <stop offset=".61" stopColor="#788187" />
            <stop offset=".72" stopColor="#657076" />
            <stop offset="1" stopColor="#8b949a" />
          </linearGradient>
          <filter id="drop-shadow-1" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron"
            data-name="Cast Iron"
            x1="298.64"
            y1="44.06"
            x2="304.38"
            y2="44.06"
            gradientTransform="translate(285.76 -260.25) rotate(78.72)"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#85878d" />
            <stop offset=".53" stopColor="#979899" />
            <stop offset="1" stopColor="#5d5c62" />
          </linearGradient>
          <filter id="drop-shadow-2" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-2" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-2" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-2"
            data-name="Pewter"
            x1="307.48"
            y1="49.84"
            x2="309.48"
            y2="49.84"
            gradientTransform="translate(-1.56 88.81) rotate(-16.34)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-3" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-3" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-3" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron-2"
            data-name="Cast Iron"
            x1="306.77"
            y1="46.69"
            x2="312.52"
            y2="46.69"
            gradientTransform="translate(294.89 -266.11) rotate(78.72)"
            xlinkHref="#Cast_Iron"
          />
          <filter id="drop-shadow-4" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-4" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-4" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-3"
            data-name="Pewter"
            x1="315.47"
            y1="52.2"
            x2="317.47"
            y2="52.2"
            gradientTransform="translate(-1.9 91.15) rotate(-16.34)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-5" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-5" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-5" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron-3"
            data-name="Cast Iron"
            x1="314.76"
            y1="49.05"
            x2="320.5"
            y2="49.05"
            gradientTransform="translate(303.63 -272.04) rotate(78.72)"
            xlinkHref="#Cast_Iron"
          />
          <filter id="drop-shadow-6" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-6" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-6" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-4"
            data-name="Pewter"
            x1="323.54"
            y1="54.62"
            x2="325.54"
            y2="54.62"
            gradientTransform="translate(-2.26 93.52) rotate(-16.34)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-7" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-7" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-7" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron-4"
            data-name="Cast Iron"
            x1="322.83"
            y1="51.47"
            x2="328.58"
            y2="51.47"
            gradientTransform="translate(312.49 -278.01) rotate(78.72)"
            xlinkHref="#Cast_Iron"
          />
          <filter id="drop-shadow-8" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-8" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-8" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-5"
            data-name="Pewter"
            x1="331.48"
            y1="57.12"
            x2="333.48"
            y2="57.12"
            gradientTransform="translate(-2.64 95.86) rotate(-16.34)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-9" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-9" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-9" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron-5"
            data-name="Cast Iron"
            x1="330.77"
            y1="53.97"
            x2="336.52"
            y2="53.97"
            gradientTransform="translate(321.33 -283.78) rotate(78.72)"
            xlinkHref="#Cast_Iron"
          />
          <filter id="drop-shadow-10" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-10" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-10" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-6"
            data-name="Pewter"
            x1="339.57"
            y1="59.72"
            x2="341.57"
            y2="59.72"
            gradientTransform="translate(-3.04 98.24) rotate(-16.34)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-11" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-11" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-11" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron-6"
            data-name="Cast Iron"
            x1="338.86"
            y1="56.57"
            x2="344.61"
            y2="56.57"
            gradientTransform="translate(330.39 -289.63) rotate(78.72)"
            xlinkHref="#Cast_Iron"
          />
          <filter id="drop-shadow-12" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-12" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-12" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="linear-gradient-2"
            x1="283.11"
            y1="58.23"
            x2="284.52"
            y2="58.23"
            gradientUnits="userSpaceOnUse"
          >
            {nutColor === "white" ? (
              <>
                <stop offset="0" stopColor="#e5e0da" />
                <stop offset=".92" stopColor="#bfbaa1" />
              </>
            ) : (
              <>
                <stop offset="0" stopColor="#656765" />
                <stop offset=".92" stopColor="#474745" />
              </>
            )}
          </linearGradient>
          <linearGradient
            id="linear-gradient-3"
            x1="116.49"
            y1="58.24"
            x2="117.5"
            y2="58.24"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset=".03" stopColor="#828487" />
            <stop offset=".17" stopColor="#909295" />
            <stop offset=".38" stopColor="#b1b3b6" />
            <stop offset=".72" stopColor="#a7a9ac" />
            <stop offset="1" stopColor="#d1d3d4" />
            <stop offset="1" stopColor="#565759" />
          </linearGradient>
          <linearGradient
            id="linear-gradient-4"
            x1="120.5"
            y1="58.23"
            x2="121.45"
            y2="58.23"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-5"
            x1="124.48"
            y1="58.21"
            x2="125.42"
            y2="58.21"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-6"
            x1="128.86"
            y1="58.24"
            x2="129.8"
            y2="58.24"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-7"
            x1="133.51"
            y1="58.21"
            x2="134.46"
            y2="58.21"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-8"
            x1="138.23"
            y1="58.28"
            x2="139.18"
            y2="58.28"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-9"
            x1="143.49"
            y1="58.25"
            x2="144.43"
            y2="58.25"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-10"
            x1="148.96"
            y1="58.23"
            x2="149.88"
            y2="58.23"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-11"
            x1="154.77"
            y1="58.24"
            x2="155.68"
            y2="58.24"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-12"
            x1="160.81"
            y1="58.28"
            x2="161.7"
            y2="58.28"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-13"
            x1="167.22"
            y1="58.25"
            x2="168.11"
            y2="58.25"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-14"
            x1="174.27"
            y1="58.3"
            x2="175.16"
            y2="58.3"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-15"
            x1="181.5"
            y1="58.2"
            x2="182.4"
            y2="58.2"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-16"
            x1="189.16"
            y1="58.24"
            x2="190.05"
            y2="58.24"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-17"
            x1="197.28"
            y1="58.3"
            x2="198.17"
            y2="58.3"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-18"
            x1="205.96"
            y1="58.28"
            x2="206.85"
            y2="58.28"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-19"
            x1="215.16"
            y1="58.25"
            x2="216.06"
            y2="58.25"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-20"
            x1="224.85"
            y1="58.32"
            x2="225.73"
            y2="58.32"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-21"
            x1="235.1"
            y1="58.32"
            x2="235.99"
            y2="58.32"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-22"
            x1="245.92"
            y1="58.33"
            x2="246.81"
            y2="58.33"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-23"
            x1="257.35"
            y1="58.27"
            x2="258.24"
            y2="58.27"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-24"
            x1="269.81"
            y1="58.36"
            x2="270.66"
            y2="58.36"
            xlinkHref="#linear-gradient-3"
          />
          <linearGradient
            id="linear-gradient-25"
            x1="106.24"
            y1="58.21"
            x2="111"
            y2="58.21"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset=".03" stopColor="#ccced1" />
            <stop offset=".22" stopColor="#bdbfc2" />
            <stop offset=".58" stopColor="#97999b" />
            <stop offset=".94" stopColor="#6b6d6e" />
          </linearGradient>
          <filter id="drop-shadow-13" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-13" stdDeviation="2" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-13" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="linear-gradient-26"
            x1="42.7"
            y1="66.1"
            x2="44.24"
            y2="66.1"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#9c9ea0" />
            <stop offset=".28" stopColor="#707173" />
            <stop offset=".92" stopColor="#030303" />
            <stop offset=".94" stopColor="#000" />
          </linearGradient>
          <linearGradient
            id="linear-gradient-27"
            y1="58.29"
            y2="58.29"
            xlinkHref="#linear-gradient-26"
          />
          <linearGradient
            id="linear-gradient-28"
            y1="50.67"
            y2="50.67"
            xlinkHref="#linear-gradient-26"
          />
          <linearGradient
            id="linear-gradient-29"
            x1="43.71"
            y1="58.27"
            x2="75.94"
            y2="58.27"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset=".15" stopColor="#8c8d8f" />
            <stop offset=".46" stopColor="#9a9b9d" />
            <stop offset=".94" stopColor="#b8babd" />
          </linearGradient>
          <linearGradient
            id="linear-gradient-30"
            x1="43.46"
            y1="58.27"
            x2="76.19"
            y2="58.27"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#6a6a6b" />
            <stop offset=".3" stopColor="#717273" />
            <stop offset=".66" stopColor="#959799" />
            <stop offset=".87" stopColor="#a3a5a7" />
            <stop offset="1" stopColor="#afb1b3" />
          </linearGradient>
          <filter id="drop-shadow-14" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-14" stdDeviation="2" />
            <feFlood flood-color="#231f20" flood-opacity="1" />
            <feComposite in2="blur-14" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="linear-gradient-31"
            x1="49.38"
            y1="51.29"
            x2="49.39"
            y2="49.77"
            gradientTransform="translate(-1.24 1.29) rotate(-1.45)"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#85878d" />
            <stop offset=".53" stopColor="#454545" />
            <stop offset="1" stopColor="#5d5c62" />
          </linearGradient>
          <linearGradient
            id="linear-gradient-32"
            x1="49.2"
            y1="59.03"
            x2="49.21"
            y2="57.51"
            xlinkHref="#linear-gradient-31"
          />
          <linearGradient
            id="linear-gradient-33"
            x1="49"
            y1="66.84"
            x2="49.01"
            y2="65.32"
            xlinkHref="#linear-gradient-31"
          />
          <filter id="drop-shadow-15" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-15" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".84" />
            <feComposite in2="blur-15" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="linear-gradient-34"
            x1="48.7"
            y1="50.17"
            x2="51.48"
            y2="50.24"
            gradientTransform="translate(.01 -1.53) rotate(-.02) scale(1 1.03)"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#85878d" />
            <stop offset=".53" stopColor="#959596" />
            <stop offset="1" stopColor="#5d5c62" />
          </linearGradient>
          <linearGradient
            id="linear-gradient-35"
            x1="49.22"
            y1="57.73"
            x2="52.01"
            y2="57.8"
            gradientTransform="translate(-1.27 -.26) rotate(-1.45) scale(1 1.03)"
            xlinkHref="#linear-gradient-34"
          />
          <linearGradient
            id="linear-gradient-36"
            x1="49.61"
            y1="65.11"
            x2="52.39"
            y2="65.18"
            gradientTransform="translate(-1.27 -.26) rotate(-1.45) scale(1 1.03)"
            xlinkHref="#linear-gradient-34"
          />
          <filter id="drop-shadow-16" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-16" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-16" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="linear-gradient-37"
            x1="69.47"
            y1="49.11"
            x2="71.15"
            y2="49.11"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset=".03" stopColor="#a7a9ac" />
            <stop offset=".59" stopColor="#b5b7ba" />
            <stop offset="1" stopColor="#c4c6c8" />
          </linearGradient>
          <linearGradient
            id="linear-gradient-38"
            x1="68.78"
            y1="52.44"
            x2="70.45"
            y2="52.44"
            xlinkHref="#linear-gradient-37"
          />
          <linearGradient
            id="linear-gradient-39"
            x1="67.94"
            y1="56.33"
            x2="69.62"
            y2="56.33"
            xlinkHref="#linear-gradient-37"
          />
          <linearGradient
            id="linear-gradient-40"
            x1="67.1"
            y1="59.91"
            x2="68.78"
            y2="59.91"
            xlinkHref="#linear-gradient-37"
          />
          <linearGradient
            id="linear-gradient-41"
            x1="66.09"
            y1="63.56"
            x2="67.77"
            y2="63.56"
            xlinkHref="#linear-gradient-37"
          />
          <linearGradient
            id="linear-gradient-42"
            x1="65.25"
            y1="67.47"
            x2="66.93"
            y2="67.47"
            xlinkHref="#linear-gradient-37"
          />
          <linearGradient
            id="Pewter-7"
            data-name="Pewter"
            x1="295.09"
            y1="51.19"
            x2="299.3"
            y2="51.19"
            gradientTransform="translate(-.72 4.11) rotate(-.74)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-17" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-17" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-17" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <radialGradient
            id="Tin_Radial"
            data-name="Tin Radial"
            cx="297.5"
            cy="51.09"
            fx="297.5"
            fy="51.09"
            r="1.35"
            gradientTransform="translate(-.72 4.11) rotate(-.74)"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#c4c6c8" />
            <stop offset=".3" stopColor="#bcbec0" />
            <stop offset=".66" stopColor="#a7a9ac" />
            <stop offset="1" stopColor="#9b9da0" />
          </radialGradient>
          <filter id="drop-shadow-18" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-18" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-18" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-8"
            data-name="Pewter"
            x1="303.22"
            y1="53.65"
            x2="307.44"
            y2="53.65"
            gradientTransform="translate(-.72 4.11) rotate(-.74)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-19" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-19" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-19" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <radialGradient
            id="Tin_Radial-2"
            data-name="Tin Radial"
            cx="305.63"
            cy="53.55"
            fx="305.63"
            fy="53.55"
            xlinkHref="#Tin_Radial"
          />
          <filter id="drop-shadow-20" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-20" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-20" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-9"
            data-name="Pewter"
            x1="311.17"
            y1="56.15"
            x2="315.38"
            y2="56.15"
            gradientTransform="translate(-.72 4.11) rotate(-.74)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-21" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-21" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-21" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <radialGradient
            id="Tin_Radial-3"
            data-name="Tin Radial"
            cx="313.58"
            cy="56.05"
            fx="313.58"
            fy="56.05"
            xlinkHref="#Tin_Radial"
          />
          <filter id="drop-shadow-22" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-22" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-22" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-10"
            data-name="Pewter"
            x1="319.29"
            y1="58.78"
            x2="323.5"
            y2="58.78"
            gradientTransform="translate(-.72 4.11) rotate(-.74)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-23" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-23" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-23" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <radialGradient
            id="Tin_Radial-4"
            data-name="Tin Radial"
            cx="321.7"
            cy="58.68"
            fx="321.7"
            fy="58.68"
            xlinkHref="#Tin_Radial"
          />
          <filter id="drop-shadow-24" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-24" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-24" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-11"
            data-name="Pewter"
            x1="327.11"
            y1="61.32"
            x2="331.32"
            y2="61.32"
            gradientTransform="translate(-.72 4.11) rotate(-.74)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-25" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-25" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-25" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <radialGradient
            id="Tin_Radial-5"
            data-name="Tin Radial"
            cx="329.52"
            cy="61.22"
            fx="329.52"
            fy="61.22"
            xlinkHref="#Tin_Radial"
          />
          <filter id="drop-shadow-26" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-26" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-26" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Pewter-12"
            data-name="Pewter"
            x1="335.31"
            y1="63.7"
            x2="339.53"
            y2="63.7"
            gradientTransform="translate(-.72 4.11) rotate(-.74)"
            xlinkHref="#Pewter"
          />
          <filter id="drop-shadow-27" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-27" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-27" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <radialGradient
            id="Tin_Radial-6"
            data-name="Tin Radial"
            cx="337.72"
            cy="63.6"
            fx="337.72"
            fy="63.6"
            r="1.35"
            xlinkHref="#Tin_Radial"
          />
          <filter id="drop-shadow-28" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-28" stdDeviation="1" />
            <feFlood flood-color="#231f20" flood-opacity=".5" />
            <feComposite in2="blur-28" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="linear-gradient-43"
            x1="18"
            y1="90.73"
            x2="74.73"
            y2="90.73"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset=".15" stopColor="#5d5e5f" />
            <stop offset=".32" stopColor="#6b6c6d" />
            <stop offset=".65" stopColor="#909294" />
            <stop offset=".94" stopColor="#b8babd" />
          </linearGradient>
          <filter id="drop-shadow-29" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-29" stdDeviation="2" />
            <feFlood flood-color="#231f20" flood-opacity=".8" />
            <feComposite in2="blur-29" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron-7"
            data-name="Cast Iron"
            x1="21.75"
            y1="90.73"
            x2="28.88"
            y2="90.73"
            gradientTransform="matrix(1,0,0,1,0,0)"
            xlinkHref="#Cast_Iron"
          />
          <filter id="drop-shadow-30" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-30" stdDeviation="2" />
            <feFlood flood-color="#231f20" flood-opacity=".8" />
            <feComposite in2="blur-30" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="Cast_Iron-8"
            data-name="Cast Iron"
            x1="44.37"
            y1="90.73"
            x2="51.5"
            y2="90.73"
            gradientTransform="matrix(1,0,0,1,0,0)"
            xlinkHref="#Cast_Iron"
          />
          <filter id="drop-shadow-31" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-31" stdDeviation="2" />
            <feFlood flood-color="#231f20" flood-opacity=".8" />
            <feComposite in2="blur-31" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <filter id="drop-shadow-32" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-32" stdDeviation="2" />
            <feFlood flood-color="#231f20" flood-opacity=".8" />
            <feComposite in2="blur-32" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
          <linearGradient
            id="linear-gradient-44"
            x1="53.69"
            y1="90.74"
            x2="59.49"
            y2="90.74"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="#3f4042" />
            <stop offset=".53" stopColor="#6a6a6b" />
            <stop offset="1" stopColor="#37373b" />
          </linearGradient>
          <filter id="drop-shadow-33" filterUnits="userSpaceOnUse">
            <feOffset dx="0" dy="0" />
            <feGaussianBlur result="blur-33" stdDeviation="2" />
            <feFlood flood-color="#231f20" flood-opacity=".8" />
            <feComposite in2="blur-33" operator="in" />
            <feComposite in="SourceGraphic" />
          </filter>
        </defs>
        <path
          id="Body"
          d="M.02,56.45c.11-12.48.54-16.73.94-19.82,1.4-10.72,2.37-17.46,7.28-23.87C13.56,5.84,20.62,3.08,22.81,2.25c14.76-5.56,29.94.65,35.6,2.97,9.99,4.09,18.92,10.68,29.26,11.46,4.25.32,8.06-.31,8.06-.31,4.56-.76,6.75-2.15,11.68-4.11,4.93-1.96,8.99-3.58,13.97-4.21,4.94-.62,10.87-1.37,16.04,2.29,3.96,2.8,7.02,7.86,7.01,12.94,0,4.56-2.46,10.8-5.37,15.26-1.1,1.69-3.05,4.33-2.23,6.9.38,1.2,1.25,2.01,1.93,2.51v18.62c-3.73-.2-6.81-.07-9.03.12-3.73.31-4.98.74-5.53.94-1.27.48-4.89,1.84-6.34,4.99-2.26,4.9,2.29,10.78,2.83,11.46,3.86,4.85,10.33,6.73,11.33,7.01,2.91.81,5.57.93,7.53,3.25.33.39,1.39,1.68,1.64,3.62,0,0,.28,2.19-.94,4.45-2.98,5.49-14.79,5.26-15.9,5.23-4.81-.14-8.44-1.34-15.51-3.75-11.02-3.74-11.17-5.28-16.18-5.8-7.14-.74-15.02,2.49-17.8,3.78-.33.15-2.27,1.16-6.13,3.18-3.63,1.89-5,2.63-7.23,3.68,0,0-2.61,1.3-5.04,2.23-5.21,2.01-11.68,4.49-20.29,4.25-3.49-.1-12.55-.48-21.3-6.61-5.36-3.75-8.53-8.19-10.11-10.79C2.17,93.63-.25,87.68.02,56.45Z"
          style={{
            fill:
              texture === "alder"
                ? "url(#BodyWoodPattern)"
                : "url(#FlamedWoodPattern)",
          }}
          stroke-width="0"
        />
        {burst && (
          <g id="Burst">
            <path
              d="M.02,56.45c.11-12.48.54-16.73.94-19.82,1.4-10.72,2.37-17.46,7.28-23.87C13.56,5.84,20.62,3.08,22.81,2.25c14.76-5.56,29.94.65,35.6,2.97,9.99,4.09,18.92,10.68,29.26,11.46,4.25.32,8.06-.31,8.06-.31,4.56-.76,6.75-2.15,11.68-4.11,4.93-1.96,8.99-3.58,13.97-4.21,4.94-.62,10.87-1.37,16.04,2.29,3.96,2.8,7.02,7.86,7.01,12.94,0,4.56-2.46,10.8-5.37,15.26-1.1,1.69-3.05,4.33-2.23,6.9.38,1.2,1.25,2.01,1.93,2.51v18.62c-3.73-.2-6.81-.07-9.03.12-3.73.31-4.98.74-5.53.94-1.27.48-4.89,1.84-6.34,4.99-2.26,4.9,2.29,10.78,2.83,11.46,3.86,4.85,10.33,6.73,11.33,7.01,2.91.81,5.57.93,7.53,3.25.33.39,1.39,1.68,1.64,3.62,0,0,.28,2.19-.94,4.45-2.98,5.49-14.79,5.26-15.9,5.23-4.81-.14-8.44-1.34-15.51-3.75-11.02-3.74-11.17-5.28-16.18-5.8-7.14-.74-15.02,2.49-17.8,3.78-.33.15-2.27,1.16-6.13,3.18-3.63,1.89-5,2.63-7.23,3.68,0,0-2.61,1.3-5.04,2.23-5.21,2.01-11.68,4.49-20.29,4.25-3.49-.1-12.55-.48-21.3-6.61-5.36-3.75-8.53-8.19-10.11-10.79C2.17,93.63-.25,87.68.02,56.45Z"
              fill="url(#linear-gradient)"
              stroke-width="0"
            />
            <g mask="url(#mask)">
              <path
                d="M.02,56.45c.11-12.48.54-16.73.94-19.82,1.4-10.72,2.37-17.46,7.28-23.87C13.56,5.84,20.62,3.08,22.81,2.25c14.76-5.56,29.94.65,35.6,2.97,9.99,4.09,18.92,10.68,29.26,11.46,4.25.32,8.06-.31,8.06-.31,4.56-.76,6.75-2.15,11.68-4.11,4.93-1.96,8.99-3.58,13.97-4.21,4.94-.62,10.87-1.37,16.04,2.29,3.96,2.8,7.02,7.86,7.01,12.94,0,4.56-2.46,10.8-5.37,15.26-1.1,1.69-3.05,4.33-2.23,6.9.38,1.2,1.25,2.01,1.93,2.51v18.62c-3.73-.2-6.81-.07-9.03.12-3.73.31-4.98.74-5.53.94-1.27.48-4.89,1.84-6.34,4.99-2.26,4.9,2.29,10.78,2.83,11.46,3.86,4.85,10.33,6.73,11.33,7.01,2.91.81,5.57.93,7.53,3.25.33.39,1.39,1.68,1.64,3.62,0,0,.28,2.19-.94,4.45-2.98,5.49-14.79,5.26-15.9,5.23-4.81-.14-8.44-1.34-15.51-3.75-11.02-3.74-11.17-5.28-16.18-5.8-7.14-.74-15.02,2.49-17.8,3.78-.33.15-2.27,1.16-6.13,3.18-3.63,1.89-5,2.63-7.23,3.68,0,0-2.61,1.3-5.04,2.23-5.21,2.01-11.68,4.49-20.29,4.25-3.49-.1-12.55-.48-21.3-6.61-5.36-3.75-8.53-8.19-10.11-10.79C2.17,93.63-.25,87.68.02,56.45Z"
                fill={burstColor}
                stroke-width="0"
              />
            </g>
          </g>
        )}
        <g id="ContourGroup">
          <path
            id="DownContourTele"
            d="M141.2,98.05c.04.43.13,2.37-.95,4.36-2.98,5.49-14.79,5.26-15.9,5.23-4.81-.14-8.44-1.34-15.51-3.75-11.02-3.74-11.17-5.28-16.18-5.8-7.14-.74-15.02,2.5-17.8,3.78-.34.16-2.27,1.17-6.14,3.19-3.62,1.89-5,2.63-7.22,3.68,0,0-2.61,1.3-5.04,2.23-5.21,2.01-11.68,4.49-20.29,4.25-3.49-.1-12.55-.48-21.3-6.61-5.36-3.75-8.53-8.19-10.11-10.79C2.38,93.98.15,88.66.01,63.7c.21,24.05,2.41,29.28,4.75,33.06,1.58,2.6,4.75,7.04,10.11,10.79,8.75,6.13,17.81,6.51,21.3,6.61,8.61.24,15.08-2.24,20.29-4.25,2.43-.94,5.04-2.24,5.04-2.24,2.22-1.05,3.6-1.79,7.22-3.68,3.87-2.02,5.8-3.03,6.14-3.18,2.78-1.29,10.66-4.52,17.8-3.78,5.01.52,5.16,2.06,16.18,5.8,7.07,2.41,10.7,3.61,15.51,3.75,1.11.03,12.92.26,15.9-5.23.67-1.24.89-2.45.95-3.3Z"
            fill="#f1f2f2"
            opacity=".37"
            stroke-width="0"
          />
          <path
            id="SideContourTele"
            d="M136.67,43.63c-.29-2.32,1.4-4.62,2.39-6.15,2.79-4.28,5.17-10.19,5.35-14.69.02.16.02.32.02.49,0,4.56-2.46,10.8-5.37,15.26-.84,1.29-2.18,3.14-2.39,5.09Z"
            fill="#f1f2f2"
            opacity=".37"
            stroke-width="0"
          />
          <path
            id="TopContourTele"
            d="M144.08,24.62c.03-.37.05-.73.05-1.07.01-4.71-3.05-9.4-7.01-11.99-5.17-3.4-11.1-2.7-16.04-2.13-4.98.59-9.04,2.09-13.97,3.91-4.93,1.81-7.12,3.1-11.68,3.81,0,0-3.81.58-8.06.28-10.34-.72-19.27-6.83-29.26-10.62-5.66-2.15-20.84-7.9-35.6-2.75-2.19.77-9.25,3.33-14.57,9.74-1.24,1.51-2.24,3.04-3.05,4.64-.01.03-.03.06-.04.08-1.76,3.5-2.65,7.37-3.42,12.18,1.2-8.1,2.46-13.61,6.81-18.87C13.56,5.41,20.62,2.85,22.81,2.09,26.59.76,30.39.16,34.06.03c1.17-.04,2.33-.04,3.47.01,9.21.4,17.13,3.64,20.88,5.18,9.99,4.09,18.92,10.68,29.26,11.46,4.25.32,8.06-.31,8.06-.31,4.56-.76,6.75-2.15,11.68-4.11s8.99-3.58,13.97-4.21c4.94-.62,10.87-1.37,16.04,2.29,3.74,2.65,6.68,7.31,6.98,12.11-.05.69-.16,1.42-.32,2.17Z"
            fill="#fff"
            opacity=".27"
            stroke-width="0"
          />
        </g>
        {hasPickguard && (
          <path
            id="Pickguard"
            d="M73.83,42.56c-.61,0-1.1-.52-1.08-1.13.19-5.23.34-8.97.37-9.41,0-.12.03-.35.19-.57.1-.14.24-.25.41-.33.59-.25,1.33-.54,2.19-.78,0,0,0,0,0,0,8.34-1.39,15.33-1.12,20.17-.59,9.52,1.04,16.11,3.65,20.14,5.28,11.19,4.53,13.66,8.46,14.66,10.73.72,1.62.99,3.1,1.11,4.12-5.06,10.6-9.56,16.16-12.83,19.31-.91.87-3.04,2.82-3.79,5.96-1.13,4.7,1.52,8.99,2.1,9.93,2.82,4.54,7.3,6.57,9.15,7.37,5.44,2.37,9.01,1.44,10.79,4.42.12.21,1.35,2.32.59,4.16-1.72,4.13-12.44,4.56-20.64,2.76-3.91-.86-5.85-1.92-21.05-7.06-3.22-1.09-4.27-1.11-5.55-1.14-4.1-.11-10.87,1.33-15.45,3.83-.55.3-2.01,1.12-2.83.57-.62-.42-.63-1.44-.58-2.14l.34-24.06c0-.6.5-1.08,1.11-1.07.68,0,1.35.01,2.03.02.72,0,1.32-.57,1.32-1.29.07-9.18.14-18.37.21-27.55,0-.71-.57-1.3-1.29-1.31l-1.76-.02Z"
            fill={pickguardColor}
            stroke="#c8c8c9"
            stroke-width=".2"
          />
        )}
        <path
          id="Fretboard"
          d="M114.43,49.51c-.02,5.81-.04,11.63-.06,17.44,0,.73.59,1.32,1.32,1.31,55.8-.78,111.61-1.56,167.41-2.34v-15.19c-55.78-.84-111.57-1.68-167.35-2.52-.73-.01-1.32.57-1.33,1.3Z"
          fill="#c49a6c"
          style={{
            fill:
              fretboardWood === "rosewood"
                ? "url(#roseWoodPattern)"
                : "url(#mapleWoodPattern)",
          }}
          strokeWidth={0.5}
          stroke="#ccc"
        />
        <g id="TuningPegs">
          <g id="_6TuningPeg" data-name="6TuningPeg">
            <rect
              id="_6TuningPegPost"
              data-name="6TuningPegPost"
              x="299.72"
              y="45.82"
              width="1.26"
              height="2.78"
              transform="translate(25.42 -82.6) rotate(16.34)"
              fill="url(#Pewter)"
              filter="url(#drop-shadow-1)"
              stroke-width="0"
            />
            <ellipse
              id="_6TuningPeg-2"
              data-name="6TuningPeg"
              cx="301.51"
              cy="44.06"
              rx="2.24"
              ry="2.9"
              transform="translate(199.35 331.14) rotate(-78.72)"
              fill="url(#Cast_Iron)"
              filter="url(#drop-shadow-2)"
              stroke-width="0"
            />
          </g>
          <g id="_5TuningPeg" data-name="5TuningPeg">
            <rect
              id="_6TuningPegPost-2"
              data-name="6TuningPegPost"
              x="307.85"
              y="48.45"
              width="1.26"
              height="2.78"
              transform="translate(26.49 -84.78) rotate(16.34)"
              fill="url(#Pewter-2)"
              filter="url(#drop-shadow-3)"
              stroke-width="0"
            />
            <ellipse
              id="_6TuningPeg-3"
              data-name="6TuningPeg"
              cx="309.64"
              cy="46.69"
              rx="2.24"
              ry="2.9"
              transform="translate(203.31 341.23) rotate(-78.72)"
              fill="url(#Cast_Iron-2)"
              filter="url(#drop-shadow-4)"
              stroke-width="0"
            />
          </g>
          <g id="_4TuningPeg" data-name="4TuningPeg">
            <rect
              id="_6TuningPegPost-3"
              data-name="6TuningPegPost"
              x="315.84"
              y="50.81"
              width="1.26"
              height="2.78"
              transform="translate(27.47 -86.94) rotate(16.34)"
              fill="url(#Pewter-3)"
              filter="url(#drop-shadow-5)"
              stroke-width="0"
            />
            <ellipse
              id="_6TuningPeg-4"
              data-name="6TuningPeg"
              cx="317.63"
              cy="49.05"
              rx="2.24"
              ry="2.9"
              transform="translate(207.42 350.96) rotate(-78.72)"
              fill="url(#Cast_Iron-3)"
              filter="url(#drop-shadow-6)"
              stroke-width="0"
            />
          </g>
          <g id="_3TuningPeg" data-name="3TuningPeg">
            <rect
              id="_6TuningPegPost-4"
              data-name="6TuningPegPost"
              x="323.91"
              y="53.23"
              width="1.26"
              height="2.78"
              transform="translate(28.48 -89.11) rotate(16.34)"
              fill="url(#Pewter-4)"
              filter="url(#drop-shadow-7)"
              stroke-width="0"
            />
            <ellipse
              id="_6TuningPeg-5"
              data-name="6TuningPeg"
              cx="325.7"
              cy="51.47"
              rx="2.24"
              ry="2.9"
              transform="translate(211.54 360.82) rotate(-78.72)"
              fill="url(#Cast_Iron-4)"
              filter="url(#drop-shadow-8)"
              stroke-width="0"
            />
          </g>
          <g id="_2TuningPeg" data-name="2TuningPeg">
            <rect
              id="_6TuningPegPost-5"
              data-name="6TuningPegPost"
              x="331.85"
              y="55.73"
              width="1.26"
              height="2.78"
              transform="translate(29.5 -91.24) rotate(16.34)"
              fill="url(#Pewter-5)"
              filter="url(#drop-shadow-9)"
              stroke-width="0"
            />
            <ellipse
              id="_6TuningPeg-6"
              data-name="6TuningPeg"
              cx="333.64"
              cy="53.97"
              rx="2.24"
              ry="2.9"
              transform="translate(215.47 370.62) rotate(-78.72)"
              fill="url(#Cast_Iron-5)"
              filter="url(#drop-shadow-10)"
              stroke-width="0"
            />
          </g>
          <g id="_1TuningPeg" data-name="1TuningPeg">
            <rect
              id="_6TuningPegPost-6"
              data-name="6TuningPegPost"
              x="339.94"
              y="58.33"
              width="1.26"
              height="2.78"
              transform="translate(30.56 -93.41) rotate(16.34)"
              fill="url(#Pewter-6)"
              filter="url(#drop-shadow-11)"
              stroke-width="0"
            />
            <ellipse
              id="_6TuningPeg-7"
              data-name="6TuningPeg"
              cx="341.73"
              cy="56.57"
              rx="2.24"
              ry="2.9"
              transform="translate(219.44 380.64) rotate(-78.72)"
              fill="url(#Cast_Iron-6)"
              filter="url(#drop-shadow-12)"
              stroke-width="0"
            />
          </g>
        </g>
        <path
          id="Headstock"
          d="M283.94,65.85c-.04-5.04-.08-10.08-.12-15.12.28.03.7.04,1.19-.08.55-.14.93-.4,1.17-.58,1.38-1.02,1.72-2.15,2.93-3.09,0,0,.61-.52,1.9-.96,2.36-.81,24.46,5.75,54.31,15.86.52.54,1.52,1.75,1.79,3.52.42,2.82-1.26,5.52-3.42,6.8-3.1,1.83-6.67.48-7.21.27-2.54-.96-3-2.49-5.65-3.17-1.75-.45-3.32-.24-4.36,0-2.81,1.48-7.01,3.07-11.5,2.49-1.76-.22-3.7-.8-3.84-.84-3.03-.9-3.53-1.62-6.67-2.8-1.54-.58-3.46-1.15-6.1-1.62-.64-.12-2.77-.52-5.65-.74-2.27-.17-5.25-.25-8.78.07Z"
          style={{
            fill: "url(#mapleWoodPattern)",
          }}
        />
        <path
          id="Nut"
          d="M283.11,50.62h.96c.25,0,.46.2.46.46v14.33c0,.25-.2.46-.46.46h-.96v-15.24h0Z"
          fill="url(#linear-gradient-2)"
        />
        <g id="FretsGroup">
          <rect
            id="Fret21"
            x="116.49"
            y="48.23"
            width="1.01"
            height="20.03"
            fill="url(#linear-gradient-3)"
            stroke-width="0"
          />
          <rect
            id="Fret20"
            x="120.5"
            y="48.29"
            width=".94"
            height="19.89"
            fill="url(#linear-gradient-4)"
            stroke-width="0"
          />
          <rect
            id="Fret19"
            x="124.48"
            y="48.35"
            width=".94"
            height="19.73"
            fill="url(#linear-gradient-5)"
            stroke-width="0"
          />
          <rect
            id="Fret18"
            x="128.86"
            y="48.41"
            width=".94"
            height="19.66"
            fill="url(#linear-gradient-6)"
            stroke-width="0"
          />
          <rect
            id="Fret17"
            x="133.51"
            y="48.41"
            width=".94"
            height="19.6"
            fill="url(#linear-gradient-7)"
            stroke-width="0"
          />
          <rect
            id="Fret16"
            x="138.23"
            y="48.55"
            width=".94"
            height="19.46"
            fill="url(#linear-gradient-8)"
            stroke-width="0"
          />
          <rect
            id="Fret15"
            x="143.49"
            y="48.63"
            width=".94"
            height="19.24"
            fill="url(#linear-gradient-9)"
            stroke-width="0"
          />
          <rect
            id="Fret15-2"
            data-name="Fret15"
            x="148.96"
            y="48.72"
            width=".92"
            height="19.02"
            fill="url(#linear-gradient-10)"
            stroke-width="0"
          />
          <rect
            id="Fret14"
            x="154.77"
            y="48.8"
            width=".91"
            height="18.87"
            fill="url(#linear-gradient-11)"
            stroke-width="0"
          />
          <rect
            id="Fret13"
            x="160.81"
            y="48.89"
            width=".89"
            height="18.78"
            fill="url(#linear-gradient-12)"
            stroke-width="0"
          />
          <rect
            id="Fret12"
            x="167.22"
            y="48.99"
            width=".89"
            height="18.51"
            fill="url(#linear-gradient-13)"
            stroke-width="0"
          />
          <rect
            id="Fret11"
            x="174.27"
            y="49.1"
            width=".89"
            height="18.41"
            fill="url(#linear-gradient-14)"
            stroke-width="0"
          />
          <rect
            id="Fret10"
            x="181.5"
            y="49.1"
            width=".89"
            height="18.21"
            fill="url(#linear-gradient-15)"
            stroke-width="0"
          />
          <rect
            id="Fret9"
            x="189.16"
            y="49.32"
            width=".89"
            height="17.85"
            fill="url(#linear-gradient-16)"
            stroke-width="0"
          />
          <rect
            id="Fret8"
            x="197.28"
            y="49.44"
            width=".89"
            height="17.72"
            fill="url(#linear-gradient-17)"
            stroke-width="0"
          />
          <rect
            id="Fret7"
            x="205.96"
            y="49.55"
            width=".89"
            height="17.45"
            fill="url(#linear-gradient-18)"
            stroke-width="0"
          />
          <rect
            id="Fret6"
            x="215.16"
            y="49.71"
            width=".89"
            height="17.09"
            fill="url(#linear-gradient-19)"
            stroke-width="0"
          />
          <rect
            id="Fret5"
            x="224.85"
            y="49.84"
            width=".87"
            height="16.96"
            fill="url(#linear-gradient-20)"
            stroke-width="0"
          />
          <rect
            id="Fret4"
            x="235.1"
            y="50.01"
            width=".89"
            height="16.62"
            fill="url(#linear-gradient-21)"
            stroke-width="0"
          />
          <rect
            id="Fret3"
            x="245.92"
            y="50.17"
            width=".89"
            height="16.32"
            fill="url(#linear-gradient-22)"
            stroke-width="0"
          />
          <rect
            id="Fret2"
            x="257.35"
            y="50.34"
            width=".89"
            height="15.84"
            fill="url(#linear-gradient-23)"
            stroke-width="0"
          />
          <rect
            id="Fret1"
            x="269.81"
            y="50.53"
            width=".85"
            height="15.66"
            fill="url(#linear-gradient-24)"
            stroke-width="0"
          />
        </g>
        <g id="DotInlaysGroup">
          <circle
            id="FretInlay3"
            cx="252.06"
            cy="58.33"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay5"
            cx="230.41"
            cy="58.36"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay7"
            cx="211.01"
            cy="58.36"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay9"
            cx="193.66"
            cy="58.33"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay12D"
            cx="171.19"
            cy="54.49"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay12U"
            cx="171.19"
            cy="62.24"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay15"
            cx="152.32"
            cy="58.36"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay17"
            cx="141.33"
            cy="58.36"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay19"
            cx="131.66"
            cy="58.36"
            r="1.38"
            fill={inlaysColor}
            stroke-width="0"
          />
          <circle
            id="FretInlay21"
            cx="122.96"
            cy="58.36"
            r="1.25"
            fill={inlaysColor}
            stroke-width="0"
          />
        </g>
        <rect
          id="NeckTelePickup"
          x="106.24"
          y="46.35"
          width="4.75"
          height="23.71"
          rx="2.38"
          ry="2.38"
          fill="url(#linear-gradient-25)"
          filter="url(#drop-shadow-13)"
          stroke-width="0"
        />
        <g id="VintageTeleBridge">
          <g id="BridgeBackScrews">
            <ellipse
              id="ScrewHead"
              cx="43.47"
              cy="66.1"
              rx=".77"
              ry=".82"
              fill="url(#linear-gradient-26)"
              stroke-width="0"
            />
            <ellipse
              id="ScrewHead-2"
              data-name="ScrewHead"
              cx="43.47"
              cy="58.29"
              rx=".77"
              ry=".82"
              fill="url(#linear-gradient-27)"
              stroke-width="0"
            />
            <ellipse
              id="ScrewHead-3"
              data-name="ScrewHead"
              cx="43.47"
              cy="50.67"
              rx=".77"
              ry=".82"
              fill="url(#linear-gradient-28)"
              stroke-width="0"
            />
          </g>
          <path
            id="VintageTeleBridgePlate"
            d="M46.78,44.45h28.62c.3,0,.54.24.54.54v26.56c0,.3-.24.54-.54.54h-28.62c-1.69,0-3.07-1.37-3.07-3.07v-21.5c0-1.69,1.37-3.07,3.07-3.07Z"
            fill="url(#linear-gradient-29)"
            filter="url(#drop-shadow-14)"
            stroke="url(#linear-gradient-30)"
            stroke-miterlimit="10"
            stroke-width=".5"
          />
          <g id="VintageTeleScrews">
            <polygon
              points="54.61 51.14 54.32 50.94 54.06 51.16 53.78 50.96 53.52 51.17 53.25 50.97 52.98 51.19 52.71 50.99 52.45 51.2 52.17 51 51.91 51.21 51.64 51.01 51.37 51.23 51.1 51.03 50.83 51.24 50.55 51.04 50.28 51.25 50.01 51.05 49.74 51.27 49.46 51.07 49.2 51.28 48.92 51.08 48.65 51.29 48.37 51.09 48.11 51.31 47.83 51.11 47.56 51.32 47.29 51.12 47.02 51.34 46.74 51.13 46.47 51.35 46.19 51.15 45.93 51.36 45.64 51.16 45.38 51.38 45.1 51.18 44.82 51.39 44.54 51.19 44.25 51.4 44.36 51.27 44.16 51.24 44.36 51.21 44.15 51.18 44.36 51.15 44.15 51.12 44.36 51.09 44.15 51.06 44.36 51.03 44.15 51 44.36 50.96 44.15 50.94 44.35 50.9 44.15 50.87 44.35 50.83 44.14 50.8 44.35 50.77 44.14 50.74 44.35 50.7 44.14 50.67 44.35 50.64 44.14 50.61 44.35 50.57 44.14 50.55 44.34 50.51 44.14 50.48 44.34 50.45 44.13 50.42 44.34 50.38 44.13 50.35 44.34 50.31 44.13 50.28 44.34 50.24 44.13 50.21 44.33 50.17 44.13 50.14 44.33 50.1 44.21 49.96 44.5 50.16 44.77 49.95 45.04 50.15 45.3 49.93 45.58 50.14 45.84 49.92 46.11 50.12 46.37 49.91 46.65 50.11 46.91 49.89 47.19 50.09 47.45 49.88 47.73 50.08 47.99 49.87 48.27 50.07 48.54 49.85 48.82 50.05 49.08 49.84 49.36 50.04 49.62 49.83 49.9 50.03 50.17 49.81 50.45 50.01 50.72 49.8 50.99 50 51.26 49.79 51.53 49.99 51.8 49.77 52.08 49.97 52.35 49.76 52.63 49.96 52.9 49.74 53.18 49.94 53.44 49.73 53.72 49.93 54 49.72 54.28 49.92 54.57 49.7 54.46 49.84 54.67 49.86 54.46 49.9 54.67 49.92 54.46 49.96 54.67 49.98 54.46 50.02 54.67 50.05 54.46 50.08 54.67 50.11 54.47 50.14 54.67 50.17 54.47 50.21 54.68 50.24 54.47 50.28 54.68 50.3 54.47 50.34 54.68 50.37 54.47 50.41 54.68 50.43 54.47 50.47 54.68 50.5 54.48 50.53 54.68 50.56 54.48 50.6 54.69 50.62 54.48 50.66 54.69 50.69 54.48 50.72 54.69 50.75 54.48 50.79 54.69 50.82 54.48 50.86 54.69 50.89 54.49 50.93 54.69 50.96 54.49 51.01 54.61 51.14"
              fill="url(#linear-gradient-31)"
              stroke-width="0"
            />
            <polygon
              points="54.63 58.88 54.34 58.68 54.07 58.9 53.8 58.69 53.53 58.91 53.26 58.71 53 58.92 52.72 58.72 52.46 58.94 52.19 58.73 51.93 58.95 51.65 58.75 51.39 58.96 51.11 58.76 50.85 58.98 50.57 58.78 50.3 58.99 50.02 58.79 49.75 59 49.48 58.8 49.21 59.02 48.94 58.82 48.67 59.03 48.39 58.83 48.12 59.04 47.84 58.84 47.58 59.06 47.3 58.86 47.03 59.07 46.75 58.87 46.49 59.08 46.21 58.88 45.94 59.1 45.66 58.9 45.39 59.11 45.11 58.91 44.84 59.13 44.55 58.93 44.27 59.14 44.38 59 44.17 58.98 44.38 58.94 44.17 58.92 44.38 58.88 44.17 58.86 44.37 58.82 44.17 58.8 44.37 58.76 44.16 58.74 44.37 58.7 44.16 58.67 44.37 58.63 44.16 58.61 44.37 58.57 44.16 58.54 44.37 58.5 44.16 58.47 44.36 58.44 44.16 58.41 44.36 58.37 44.15 58.35 44.36 58.31 44.15 58.28 44.36 58.25 44.15 58.22 44.36 58.18 44.15 58.16 44.36 58.12 44.15 58.09 44.35 58.05 44.15 58.02 44.35 57.98 44.14 57.95 44.35 57.91 44.14 57.88 44.35 57.84 44.23 57.7 44.52 57.9 44.78 57.68 45.05 57.88 45.32 57.67 45.59 57.87 45.85 57.66 46.13 57.86 46.39 57.64 46.66 57.84 46.93 57.63 47.2 57.83 47.46 57.62 47.74 57.82 48.01 57.6 48.28 57.8 48.55 57.59 48.83 57.79 49.1 57.58 49.37 57.78 49.64 57.56 49.92 57.76 50.18 57.55 50.46 57.75 50.73 57.54 51.01 57.74 51.27 57.52 51.55 57.72 51.82 57.51 52.1 57.71 52.36 57.49 52.64 57.69 52.91 57.48 53.19 57.68 53.46 57.47 53.74 57.67 54.01 57.45 54.3 57.65 54.58 57.44 54.47 57.57 54.68 57.6 54.48 57.63 54.68 57.66 54.48 57.69 54.68 57.72 54.48 57.76 54.69 57.78 54.48 57.82 54.69 57.84 54.48 57.88 54.69 57.91 54.48 57.95 54.69 57.97 54.48 58.01 54.69 58.04 54.49 58.08 54.69 58.1 54.49 58.14 54.7 58.17 54.49 58.21 54.7 58.23 54.49 58.27 54.7 58.3 54.49 58.33 54.7 58.36 54.49 58.4 54.7 58.42 54.5 58.46 54.7 58.49 54.5 58.53 54.71 58.56 54.5 58.6 54.71 58.63 54.5 58.67 54.71 58.7 54.5 58.75 54.63 58.88"
              fill="url(#linear-gradient-32)"
              stroke-width="0"
            />
            <polygon
              points="54.63 66.69 54.34 66.49 54.07 66.71 53.8 66.51 53.53 66.72 53.26 66.52 53 66.73 52.72 66.53 52.46 66.75 52.19 66.55 51.93 66.76 51.65 66.56 51.39 66.78 51.11 66.57 50.85 66.79 50.57 66.59 50.3 66.8 50.02 66.6 49.75 66.82 49.48 66.62 49.21 66.83 48.94 66.63 48.67 66.84 48.39 66.64 48.12 66.86 47.84 66.66 47.58 66.87 47.3 66.67 47.03 66.88 46.75 66.68 46.49 66.9 46.21 66.7 45.94 66.91 45.66 66.71 45.39 66.93 45.11 66.73 44.84 66.94 44.55 66.74 44.27 66.95 44.38 66.82 44.17 66.79 44.38 66.76 44.17 66.73 44.38 66.7 44.17 66.67 44.37 66.64 44.17 66.61 44.37 66.57 44.16 66.55 44.37 66.51 44.16 66.48 44.37 66.45 44.16 66.42 44.37 66.38 44.16 66.35 44.37 66.31 44.16 66.29 44.36 66.25 44.16 66.22 44.36 66.19 44.15 66.16 44.36 66.12 44.15 66.1 44.36 66.06 44.15 66.03 44.36 66 44.15 65.97 44.36 65.93 44.15 65.9 44.35 65.86 44.15 65.83 44.35 65.79 44.14 65.76 44.35 65.72 44.14 65.69 44.35 65.65 44.23 65.51 44.52 65.71 44.78 65.5 45.05 65.7 45.32 65.48 45.59 65.68 45.85 65.47 46.13 65.67 46.39 65.46 46.66 65.66 46.93 65.44 47.2 65.64 47.46 65.43 47.74 65.63 48.01 65.42 48.28 65.62 48.55 65.4 48.83 65.6 49.1 65.39 49.37 65.59 49.64 65.38 49.92 65.58 50.18 65.36 50.46 65.56 50.73 65.35 51.01 65.55 51.27 65.33 51.55 65.54 51.82 65.32 52.1 65.52 52.36 65.31 52.64 65.51 52.91 65.29 53.19 65.49 53.46 65.28 53.74 65.48 54.01 65.27 54.3 65.47 54.58 65.25 54.47 65.39 54.68 65.41 54.48 65.45 54.68 65.47 54.48 65.51 54.68 65.53 54.48 65.57 54.69 65.59 54.48 65.63 54.69 65.66 54.48 65.69 54.69 65.72 54.48 65.76 54.69 65.79 54.48 65.82 54.69 65.85 54.49 65.89 54.69 65.92 54.49 65.96 54.7 65.98 54.49 66.02 54.7 66.05 54.49 66.08 54.7 66.11 54.49 66.15 54.7 66.17 54.49 66.21 54.7 66.24 54.5 66.27 54.7 66.3 54.5 66.34 54.71 66.37 54.5 66.41 54.71 66.44 54.5 66.48 54.71 66.51 54.5 66.56 54.63 66.69"
              fill="url(#linear-gradient-33)"
              stroke-width="0"
            />
          </g>
          <g id="VintageTeleSaddles" filter="url(#drop-shadow-15)">
            <path
              d="M49.17,46.5h1.9c.2,0,.35.16.35.35v7.07c0,.19-.16.35-.35.35h-1.9c-.2,0-.35-.16-.35-.35v-7.07c0-.19.16-.35.35-.35Z"
              transform="translate(-1.25 1.27) rotate(-1.43)"
              fill="url(#linear-gradient-34)"
              stroke-width="0"
            />
            <path
              d="M51.89,62.06l-1.89.05c-.2,0-.36-.15-.37-.34l-.18-7.07c0-.2.15-.36.35-.36l1.89-.05c.2,0,.36.15.37.34l.18,7.07c0,.2-.15.36-.35.36Z"
              fill="url(#linear-gradient-35)"
              stroke-width="0"
            />
            <path
              d="M52.47,69.68l-1.89.05c-.2,0-.36-.15-.37-.34l-.18-7.07c0-.2.15-.36.35-.36l1.89-.05c.2,0,.36.15.37.34l.18,7.07c0,.2-.15.36-.35.36Z"
              fill="url(#linear-gradient-36)"
              stroke-width="0"
            />
          </g>
          <g id="VintageTeleSaddleScrew">
            <polygon
              id="SaddleScrew"
              points="50.36 47.72 49.95 47.84 49.63 47.55 49.73 47.14 50.14 47.02 50.46 47.31 50.36 47.72"
              fill="#323233"
              stroke-width="0"
            />
            <polygon
              id="SaddleScrew-2"
              data-name="SaddleScrew"
              points="50.51 53.59 50.1 53.71 49.78 53.42 49.88 53.01 50.29 52.88 50.61 53.17 50.51 53.59"
              fill="#323233"
              stroke-width="0"
            />
            <polygon
              id="SaddleScrew-3"
              data-name="SaddleScrew"
              points="51.09 55.68 50.68 55.8 50.36 55.51 50.46 55.1 50.87 54.97 51.19 55.26 51.09 55.68"
              fill="#323233"
              stroke-width="0"
            />
            <polygon
              id="SaddleScrew-4"
              data-name="SaddleScrew"
              points="51.3 61.06 50.89 61.19 50.57 60.89 50.67 60.48 51.08 60.36 51.4 60.65 51.3 61.06"
              fill="#323233"
              stroke-width="0"
            />
            <polygon
              id="SaddleScrew-5"
              data-name="SaddleScrew"
              points="51.66 63.14 51.25 63.26 50.93 62.97 51.03 62.56 51.44 62.43 51.76 62.72 51.66 63.14"
              fill="#323233"
              stroke-width="0"
            />
            <polygon
              id="SaddleScrew-6"
              data-name="SaddleScrew"
              points="51.81 69.08 51.4 69.2 51.09 68.91 51.18 68.49 51.6 68.37 51.91 68.66 51.81 69.08"
              fill="#323233"
              stroke-width="0"
            />
          </g>
        </g>
        <g id="BridgeTelePickup" filter="url(#drop-shadow-16)">
          <path
            id="BridgePickup"
            d="M65.74,69.64l-.47-.11c-1.32-.3-2.14-1.61-1.83-2.91l4.45-18.8c.31-1.3,1.63-2.11,2.95-1.81l.47.11c1.32.3,2.14,1.61,1.83,2.91l-4.45,18.8c-.31,1.3-1.63,2.11-2.95,1.81Z"
            fill="#232020"
            stroke-width="0"
          />
          <g id="BridgePickupPoles">
            <circle
              id="SimplePickupPole"
              cx="70.31"
              cy="49.11"
              r=".84"
              fill="url(#linear-gradient-37)"
              stroke-width="0"
            />
            <circle
              id="SimplePickupPole-2"
              data-name="SimplePickupPole"
              cx="69.62"
              cy="52.44"
              r=".84"
              fill="url(#linear-gradient-38)"
              stroke-width="0"
            />
            <circle
              id="SimplePickupPole-3"
              data-name="SimplePickupPole"
              cx="68.78"
              cy="56.33"
              r=".84"
              fill="url(#linear-gradient-39)"
              stroke-width="0"
            />
            <circle
              id="SimplePickupPole-4"
              data-name="SimplePickupPole"
              cx="67.94"
              cy="59.91"
              r=".84"
              fill="url(#linear-gradient-40)"
              stroke-width="0"
            />
            <circle
              id="SimplePickupPole-5"
              data-name="SimplePickupPole"
              cx="66.93"
              cy="63.56"
              r=".84"
              fill="url(#linear-gradient-41)"
              stroke-width="0"
            />
            <circle
              id="SimplePickupPole-6"
              data-name="SimplePickupPole"
              cx="66.09"
              cy="67.47"
              r=".84"
              fill="url(#linear-gradient-42)"
              stroke-width="0"
            />
          </g>
        </g>
        <g id="Strings">
          <polyline
            id="_6String"
            data-name="6String"
            points="45.82 48.83 284.52 51.49 296.07 51.36"
            fill="none"
            stroke="#bcbec0"
            stroke-miterlimit="10"
            stroke-width=".25"
          />
          <polyline
            id="_5String"
            data-name="5String"
            points="45.78 52.25 284.78 54.18 305.33 54.34"
            fill="none"
            stroke="#bcbec0"
            stroke-miterlimit="10"
            stroke-width=".25"
          />
          <polyline
            id="_4String"
            data-name="4String"
            points="46.14 56.27 284.73 56.89 313.27 56.97"
            fill="none"
            stroke="#bcbec0"
            stroke-miterlimit="10"
            stroke-width=".25"
          />
          <polyline
            id="_3String"
            data-name="3String"
            points="46.29 60 284.83 59.03 320.37 58.89"
            fill="none"
            stroke="#bcbec0"
            stroke-miterlimit="10"
            stroke-width=".25"
          />
          <polyline
            id="_2String"
            data-name="2String"
            points="46.32 63.73 285.48 61.79 328.28 61.44"
            fill="none"
            stroke="#bcbec0"
            stroke-miterlimit="10"
            stroke-width=".25"
          />
          <path
            id="_1String"
            data-name="1String"
            d="M47.29,67.81c79.27-1.03,158.55-2.05,237.82-3.08,14.44-.19,36.98-.81,51.41-1"
            fill="none"
            stroke="#bcbec0"
            stroke-miterlimit="10"
            stroke-width=".25"
          />
        </g>
        <g id="TuningPosts">
          <g id="_6TuningPost" data-name="6TuningPost">
            <circle
              cx="297.12"
              cy="51.45"
              r="2.11"
              fill="url(#Pewter-7)"
              filter="url(#drop-shadow-17)"
              stroke-width="0"
            />
            <circle
              cx="297.42"
              cy="51.35"
              r="1.35"
              fill="url(#Tin_Radial)"
              filter="url(#drop-shadow-18)"
              stroke-width="0"
            />
          </g>
          <g id="_5TuningPost" data-name="5TuningPost">
            <circle
              cx="305.28"
              cy="53.81"
              r="2.11"
              fill="url(#Pewter-8)"
              filter="url(#drop-shadow-19)"
              stroke-width="0"
            />
            <circle
              cx="305.58"
              cy="53.7"
              r="1.35"
              fill="url(#Tin_Radial-2)"
              filter="url(#drop-shadow-20)"
              stroke-width="0"
            />
          </g>
          <g id="_4TuningPost" data-name="4TuningPost">
            <circle
              cx="313.26"
              cy="56.21"
              r="2.11"
              fill="url(#Pewter-9)"
              filter="url(#drop-shadow-21)"
              stroke-width="0"
            />
            <circle
              cx="313.56"
              cy="56.1"
              r="1.35"
              fill="url(#Tin_Radial-3)"
              filter="url(#drop-shadow-22)"
              stroke-width="0"
            />
          </g>
          <g id="_3TuningPost" data-name="3TuningPost">
            <circle
              cx="321.41"
              cy="58.73"
              r="2.11"
              fill="url(#Pewter-10)"
              filter="url(#drop-shadow-23)"
              stroke-width="0"
            />
            <circle
              cx="321.72"
              cy="58.63"
              r="1.35"
              fill="url(#Tin_Radial-4)"
              filter="url(#drop-shadow-24)"
              stroke-width="0"
            />
          </g>
          <g id="_2TuningPost" data-name="2TuningPost">
            <circle
              cx="329.27"
              cy="61.17"
              r="2.11"
              fill="url(#Pewter-11)"
              filter="url(#drop-shadow-25)"
              stroke-width="0"
            />
            <circle
              cx="329.57"
              cy="61.06"
              r="1.35"
              fill="url(#Tin_Radial-5)"
              filter="url(#drop-shadow-26)"
              stroke-width="0"
            />
          </g>
          <g id="_1TuningPost" data-name="1TuningPost">
            <circle
              cx="337.5"
              cy="63.44"
              r="2.11"
              fill="url(#Pewter-12)"
              filter="url(#drop-shadow-27)"
              stroke-width="0"
            />
            <circle
              cx="337.8"
              cy="63.33"
              r="1.35"
              fill="url(#Tin_Radial-6)"
              filter="url(#drop-shadow-28)"
              stroke-width="0"
            />
          </g>
        </g>
        <g id="TeleElectronicsControls">
          <rect
            id="TeleElectronicsPlate"
            x="18"
            y="84.97"
            width="56.73"
            height="11.53"
            rx="5.76"
            ry="5.76"
            fill="url(#linear-gradient-43)"
            filter="url(#drop-shadow-29)"
            stroke-width="0"
          />
          <circle
            id="Knob"
            cx="25.32"
            cy="90.73"
            r="3.56"
            fill="url(#Cast_Iron-7)"
            filter="url(#drop-shadow-30)"
            stroke-width="0"
          />
          <circle
            id="Knob-2"
            data-name="Knob"
            cx="47.93"
            cy="90.73"
            r="3.56"
            fill="url(#Cast_Iron-8)"
            filter="url(#drop-shadow-31)"
            stroke-width="0"
          />
          <rect
            x="55.92"
            y="89.77"
            width="11.46"
            height="1.94"
            rx=".97"
            ry=".97"
            fill="#231f20"
            filter="url(#drop-shadow-32)"
            stroke-width="0"
          />
          <path
            id="PickupSwitchBlade"
            d="M59.49,90.16v1.17c0,.64-.53,1.17-1.17,1.17h-2.87c-.06,0-.12,0-.18-.02-.89-.08-1.58-.83-1.58-1.74s.69-1.66,1.58-1.74c.03-.01.06-.02.09-.01h2.96c.64,0,1.17.52,1.17,1.17Z"
            fill="url(#linear-gradient-44)"
            filter="url(#drop-shadow-33)"
            stroke-width="0"
          />
        </g>
      </svg>
    </>
  );
};

export default Guitar;
