const Patterns = ({ color, bodyPaintOpacity }) => {
  return (
    <>
      {/* Body patterns */}
      <pattern
        id="BodyWoodPattern"
        patternUnits="objectBoundingBox"
        width="1"
        height="1"
      >
        <image
          href="/wood.jpg"
          preserveAspectRatio="none"
          width="100%"
          height="100%"
        />
        <rect
          width="100%"
          height="100%"
          fill={color}
          opacity={bodyPaintOpacity}
        />
      </pattern>
      <pattern
        id="FlamedWoodPattern"
        patternUnits="objectBoundingBox"
        width="1"
        height="1"
      >
        <image
          href="/flamedMaple.jpg"
          preserveAspectRatio="none"
          width="100%"
          height="100%"
        />
        <rect
          width="100%"
          height="100%"
          fill={color}
          opacity={bodyPaintOpacity}
        />
      </pattern>
      {/* Neck patterns */}
      <pattern
        id="mapleWoodPattern"
        patternUnits="objectBoundingBox"
        width="1"
        height="1"
      >
        <image
          href="/maple.jpg"
          preserveAspectRatio="none"
          width="190px"
          height="190px"
        />
      </pattern>
      <pattern
        id="roseWoodPattern"
        patternUnits="objectBoundingBox"
        width="1"
        height="1"
      >
        <image
          href="/rosewood.jpg"
          preserveAspectRatio="none"
          width="190px"
          height="190px"
        />
      </pattern>
    </>
  );
};

export default Patterns;
